name: Game CI
on:
    workflow_dispatch: {}
jobs:
    Game-CI:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                projectPath:
                    - ./
        steps:
            - name: Build
              uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  projectPath: ./
                  targetPlatform: WebGL
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                  name: Build
                  path: build
